package main

/*
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
*/
import "C"

import (
	"context"
	"fmt"
	"runtime"
	"runtime/debug"
	"sync"
	"unsafe"

	box "github.com/sagernet/sing-box"
	"github.com/sagernet/sing-box/constant"
	"github.com/sagernet/sing-box/include"
	"github.com/sagernet/sing-box/option"
	"github.com/sagernet/sing/common/json"
)

// ---------- state ----------

var (
	mu        sync.Mutex
	instance  *box.Box
	cancelFn  context.CancelFunc
	running   bool
	lastError string
	homeDir   string

	// Cached port values for Swift to query after start
	cachedSocksPort int32
	cachedDNSPort   int32
	cachedCtrlAddr  string
)

// ---------- error helpers ----------

func setError(msg string) {
	lastError = msg
}

//export bridge_get_last_error
func bridge_get_last_error() *C.char {
	return C.CString(lastError)
}

//export bridge_free_string
func bridge_free_string(ptr *C.char) {
	C.free(unsafe.Pointer(ptr))
}

// ---------- home dir ----------

//export bridge_set_home_dir
func bridge_set_home_dir(dir *C.char) {
	if dir == nil {
		return
	}
	homeDir = C.GoString(dir)
}

// ---------- log file (no-op for sing-box; log path is in JSON config) ----------

//export bridge_set_log_file
func bridge_set_log_file(path *C.char) C.int32_t {
	// sing-box log output path is set inside the JSON config.
	// This is a no-op shim kept for ABI compatibility with the Swift layer.
	return 0
}

// ---------- start ----------

//export bridge_start_with_config
func bridge_start_with_config(
	socks_port C.int32_t,
	dns_port C.int32_t,
	controller_addr *C.char,
	secret *C.char,
	config_json *C.char,
) C.int32_t {
	mu.Lock()
	defer mu.Unlock()

	if running {
		setError("proxy is already running")
		return -1
	}

	if config_json == nil {
		setError("config_json is null")
		return -1
	}

	configBytes := []byte(C.GoString(config_json))

	// Parse JSON config using sing-box's own JSON library
	ctx := context.Background()
	ctx = box.Context(
		ctx,
		include.InboundRegistry(),
		include.OutboundRegistry(),
		include.EndpointRegistry(),
	)
	var opts option.Options
	if err := json.UnmarshalContext(ctx, configBytes, &opts); err != nil {
		setError(fmt.Sprintf("parse config: %v", err))
		return -1
	}

	// The JSON generated by Swift already contains the correct ports and clash_api config.
	// We just need to store them for the getter functions.
	sp := int(socks_port)
	dp := int(dns_port)
	ctrlAddr := ""
	if controller_addr != nil {
		ctrlAddr = C.GoString(controller_addr)
	}

	// Create and start sing-box instance
	runCtx, cancel := context.WithCancel(ctx)
	inst, err := box.New(box.Options{
		Context: runCtx,
		Options: opts,
	})
	if err != nil {
		cancel()
		setError(fmt.Sprintf("box.New: %v", err))
		return -1
	}
	if err := inst.Start(); err != nil {
		cancel()
		setError(fmt.Sprintf("box.Start: %v", err))
		return -1
	}

	instance = inst
	cancelFn = cancel
	running = true
	cachedSocksPort = int32(sp)
	cachedDNSPort = int32(dp)
	cachedCtrlAddr = ctrlAddr

	runtime.GC()
	debug.FreeOSMemory()
	return 0
}

// ---------- stop ----------

//export bridge_stop_proxy
func bridge_stop_proxy() {
	mu.Lock()
	defer mu.Unlock()

	if !running {
		return
	}
	if cancelFn != nil {
		cancelFn()
		cancelFn = nil
	}
	if instance != nil {
		_ = instance.Close()
		instance = nil
	}
	running = false
	cachedSocksPort = 0
	cachedDNSPort = 0
	cachedCtrlAddr = ""
	runtime.GC()
	debug.FreeOSMemory()
}

// ---------- status ----------

//export bridge_is_running
func bridge_is_running() C.bool {
	mu.Lock()
	defer mu.Unlock()
	return C.bool(running)
}

//export bridge_get_socks_port
func bridge_get_socks_port() C.int32_t {
	mu.Lock()
	defer mu.Unlock()
	return C.int32_t(cachedSocksPort)
}

//export bridge_get_dns_port
func bridge_get_dns_port() C.int32_t {
	mu.Lock()
	defer mu.Unlock()
	return C.int32_t(cachedDNSPort)
}

//export bridge_get_external_controller_addr
func bridge_get_external_controller_addr() *C.char {
	mu.Lock()
	defer mu.Unlock()
	if cachedCtrlAddr == "" {
		return nil
	}
	return C.CString(cachedCtrlAddr)
}

// ---------- traffic (queried via REST API in Swift; these are stubs) ----------

//export bridge_get_upload_traffic
func bridge_get_upload_traffic() C.int64_t {
	return 0
}

//export bridge_get_download_traffic
func bridge_get_download_traffic() C.int64_t {
	return 0
}

// ---------- misc ----------

//export bridge_force_gc
func bridge_force_gc() {
	runtime.GC()
	debug.FreeOSMemory()
}

//export bridge_version
func bridge_version() *C.char {
	return C.CString("sing-box " + constant.Version)
}

// Validate config JSON (parse-only, no start)
//export bridge_validate_config
func bridge_validate_config(config_json *C.char) C.int32_t {
	if config_json == nil {
		setError("config_json is null")
		return -1
	}
	configBytes := []byte(C.GoString(config_json))
	ctx := box.Context(
		context.Background(),
		include.InboundRegistry(),
		include.OutboundRegistry(),
		include.EndpointRegistry(),
	)
	var opts option.Options
	if err := json.UnmarshalContext(ctx, configBytes, &opts); err != nil {
		setError(fmt.Sprintf("invalid config: %v", err))
		return -1
	}
	return 0
}

//export bridge_update_log_level
func bridge_update_log_level(level *C.char) {
	// no-op stub for ABI compatibility
}
